name: papermage
channels:
  - defaults
dependencies:
  - boost-cpp=1.82.0=ha357a0b_2
  - bzip2=1.0.8=h6c40b1e_6
  - c-ares=1.19.1=h6c40b1e_0
  - ca-certificates=2025.7.15=hecd8cb5_0
  - cairo=1.16.0=h08824b9_6
  - expat=2.7.1=h6d0c2b6_0
  - fontconfig=2.14.1=h269ac6a_3
  - freetype=2.13.3=h02243ff_0
  - gettext=0.21.0=h4e8c18a_2
  - icu=73.1=hcec6c5f_0
  - jpeg=9e=h46256e1_3
  - lcms2=2.16=h31d93a5_1
  - lerc=4.0.0=h6d0c2b6_0
  - libboost=1.82.0=hf53b9f2_2
  - libcurl=8.14.1=h1448931_1
  - libcxx=19.1.7=haebbb44_3
  - libdeflate=1.22=h46256e1_0
  - libev=4.33=h9ed2024_1
  - libffi=3.4.4=hecd8cb5_1
  - libglib=2.84.2=heb90364_0
  - libiconv=1.16=h6c40b1e_3
  - libnghttp2=1.57.0=h9beae6a_0
  - libpng=1.6.39=h6c40b1e_0
  - libssh2=1.11.1=h3a17b82_0
  - libtiff=4.7.0=h2dfa3ea_0
  - libwebp-base=1.3.2=h46256e1_1
  - libxml2=2.13.8=h6070cd6_0
  - llvm-openmp=19.1.7=h5048363_2
  - lz4-c=1.9.4=hcec6c5f_1
  - ncurses=6.5=h923df54_0
  - nspr=4.35=hcec6c5f_0
  - nss=3.89.1=hcec6c5f_0
  - openjpeg=2.5.2=h2d09ccc_1
  - openssl=3.0.17=hee2dfae_0
  - pcre2=10.42=h9b97e30_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=hb254d66_0
  - poppler=24.09.0=h1093dcf_3
  - poppler-data=0.4.11=hecd8cb5_1
  - python=3.9.23=hd8516d5_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py39hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - wheel=0.45.1=py39hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - zstd=1.5.6=h138b38a_0
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - anyio==4.12.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - boltons==25.0.0
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - cryptography==46.0.3
    - datasets==4.4.1
    - dill==0.4.0
    - distro==1.9.0
    - effdet==0.4.1
    - exceptiongroup==1.3.1
    - face==24.0.0
    - filelock==3.19.1
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - ftfy==6.3.1
    - glom==24.11.0
    - grobid-client-python==0.0.5
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - idna==3.11
    - iniconfig==2.1.0
    - iopath==0.1.10
    - jinja2==3.1.6
    - jiter==0.12.0
    - joblib==1.5.2
    - layoutparser==0.3.4
    - markupsafe==3.0.3
    - mpmath==1.3.0
    - multidict==6.7.0
    - multiprocess==0.70.18
    - ncls==0.0.68
    - necessary==0.4.3
    - networkx==3.2.1
    - numpy==1.26.4
    - omegaconf==2.3.0
    - openai==2.11.0
    - opencv-python==4.9.0.80
    - packaging==25.0
    - pandas==2.3.3
    - papermage==0.20.0
    - pdf2image==1.17.0
    - pdfminer-six==20220524
    - pdfplumber==0.7.4
    - pillow==11.3.0
    - platformdirs==4.4.0
    - pluggy==1.6.0
    - portalocker==3.2.0
    - propcache==0.4.1
    - pyarrow==21.0.0
    - pycocotools==2.0.10
    - pycparser==2.23
    - pydantic==2.12.5
    - pydantic-core==2.41.5
    - pygments==2.19.2
    - pysbd==0.3.4
    - pytest==8.4.2
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - pyyaml==6.0.3
    - regex==2025.11.3
    - requests==2.32.5
    - requirements-parser==0.13.0
    - safetensors==0.7.0
    - scikit-learn==1.6.1
    - scipy==1.13.1
    - six==1.17.0
    - smashed==0.21.5
    - sniffio==1.3.1
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - timm==1.0.22
    - tokenizers==0.20.3
    - tomli==2.3.0
    - torch==2.2.2
    - torchaudio==2.2.2
    - torchvision==0.17.2
    - tqdm==4.67.1
    - transformers==4.45.2
    - trouting==0.3.3
    - typing-extensions==4.15.0
    - typing-inspection==0.4.2
    - tzdata==2025.2
    - urllib3==2.6.1
    - vila==0.5.0
    - wand==0.6.13
    - wcwidth==0.2.14
    - xxhash==3.6.0
    - yarl==1.22.0
prefix: /Users/madeleinevanzuylen/opt/anaconda3/envs/papermage
